//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PY { get; set; }
        public string EnglishName { get; set; }
        public string Company { get; set; }
        public string ProductPlace { get; set; }
        public string WebSite { get; set; }
        public string Image { get; set; }
        public int Hot { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
