//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Telphone { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public int HasSub { get; set; }
        public string ComPath { get; set; }
        public int ParentId { get; set; }
        public int TypeId { get; set; }
        public string Status { get; set; }
        public string EmployeesNum { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Street { get; set; }
        public string Mansion { get; set; }
        public string Room { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int InnerUserId { get; set; }
        public string RegisterMethod { get; set; }
        public string PY { get; set; }
    }
}
