//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyGCPP
    {
        public int Id { get; set; }
        public int ComId { get; set; }
        public int ParentId { get; set; }
        public int HasSub { get; set; }
        public int CompanyLevel { get; set; }
        public int Level1ComId { get; set; }
        public int Level2ComId { get; set; }
        public int OrderLevel { get; set; }
        public int ComfirmLevel { get; set; }
    }
}
