//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public int ComId { get; set; }
        public int ModelId { get; set; }
        public int Level { get; set; }
        public int SalesId { get; set; }
        public int ServiceId { get; set; }
        public string StatementMan { get; set; }
        public Nullable<decimal> MonthSales { get; set; }
        public string OrderMemo { get; set; }
        public string PackageType { get; set; }
        public string PackageMemo { get; set; }
        public string Sign { get; set; }
        public string DeliveryMemo { get; set; }
        public string PayType { get; set; }
        public string PayMethod { get; set; }
        public decimal Credit { get; set; }
        public int CreditDays { get; set; }
        public string StatementMemo { get; set; }
        public string InvoiceType { get; set; }
        public string Invoice_Name { get; set; }
        public string Invoice_TaxNo { get; set; }
        public string Invoice_Address { get; set; }
        public string Invoice_Phone { get; set; }
        public string Invoice_Bank { get; set; }
        public string Invoice_BankAccount { get; set; }
        public string InvoiceMemo { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int StartOrder { get; set; }
        public int StatementManId { get; set; }
        public int IsSPAssess { get; set; }
        public int BranchId { get; set; }
        public int IsNational { get; set; }
        public int ConfirmLevel { get; set; }
        public int IsPass { get; set; }
        public string Invoice_Content { get; set; }
        public int IsManyNum { get; set; }
        public int IsComfirmOrder { get; set; }
        public int IsCounter { get; set; }
        public int IsBudget { get; set; }
        public int IsArchive { get; set; }
        public int OrderPrintNum { get; set; }
        public int IsDownloadOrder { get; set; }
        public int IsBuyOutCounter { get; set; }
        public int IsStoreManager { get; set; }
        public int IsAgainConfirm { get; set; }
        public string IsBanningOrders { get; set; }
        public int IsOrderConfig { get; set; }
        public double TaxRate { get; set; }
    }
}
