//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dept
    {
        public int Id { get; set; }
        public int ComId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string PCode { get; set; }
        public int Level { get; set; }
        public int IsCalc { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int BranchId { get; set; }
        public int IsSepareOrder { get; set; }
        public int SecrecyId { get; set; }
        public System.DateTime ExportDate { get; set; }
    }
}
