//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_bak20170929
    {
        public int ID { get; set; }
        public int BranchId { get; set; }
        public int BrandId { get; set; }
        public string SN { get; set; }
        public int TypeId { get; set; }
        public int SupplierId { get; set; }
        public string GoodsName { get; set; }
        public string DisplayName { get; set; }
        public string PY { get; set; }
        public string Feature { get; set; }
        public string Unit { get; set; }
        public string Model { get; set; }
        public string Package { get; set; }
        public Nullable<decimal> MarketPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> InPrice { get; set; }
        public Nullable<decimal> TaxInPrice { get; set; }
        public string Description { get; set; }
        public string PackingList { get; set; }
        public string Service { get; set; }
        public int IsVisible { get; set; }
        public int Recommend { get; set; }
        public Nullable<System.DateTime> RecommendDate { get; set; }
        public decimal cuxiao { get; set; }
        public System.DateTime cuxiaoDate { get; set; }
        public int IsNew { get; set; }
        public int IsHot { get; set; }
        public int Rate { get; set; }
        public string HomeImage { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public Nullable<decimal> Maolilv { get; set; }
        public Nullable<int> AllBarCodeNum { get; set; }
        public Nullable<int> BarCodeNum { get; set; }
        public Nullable<int> PhotoNum { get; set; }
        public int IsShelves { get; set; }
        public int IsAllow { get; set; }
        public int IsPublic { get; set; }
        public int ParentId { get; set; }
        public int ModelId { get; set; }
        public int UserId { get; set; }
        public int SaleNumber { get; set; }
        public int SaleCount { get; set; }
        public string EnGoodsName { get; set; }
        public string EnDisplayName { get; set; }
        public int IsSoldOutStop { get; set; }
        public string Memo { get; set; }
        public string GoodsRank { get; set; }
        public string Origin { get; set; }
        public string ShelfLife { get; set; }
        public string ReJectMsg { get; set; }
        public string JD_Link { get; set; }
        public Nullable<decimal> JD_Price { get; set; }
    }
}
