//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsBranch
    {
        public int Id { get; set; }
        public int GoodsId { get; set; }
        public int BranchId { get; set; }
        public int IsVisible { get; set; }
        public int IsAllow { get; set; }
        public int IsPublic { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> IsWeb { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> PriceRate { get; set; }
        public int IsChangePrice { get; set; }
        public int IsChangeRecommend { get; set; }
        public int Recommend { get; set; }
    }
}
