//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsType
    {
        public int ID { get; set; }
        public string TypeName { get; set; }
        public string Code { get; set; }
        public string PCode { get; set; }
        public int Level { get; set; }
        public int PriceRate { get; set; }
        public string Alias { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public string GuiGe { get; set; }
        public string JiaGe { get; set; }
        public string BieMing { get; set; }
        public int SortId { get; set; }
        public int rate { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string EnTypeName { get; set; }
        public string PY { get; set; }
    }
}
