//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public int BranchId { get; set; }
        public int ComId { get; set; }
        public int OrderStatementId { get; set; }
        public int InvoiceRequireId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceType { get; set; }
        public decimal InvoiceMoney { get; set; }
        public string Memo { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int UserId { get; set; }
        public int PrintNum { get; set; }
        public System.DateTime PrintTime { get; set; }
        public string InvoiceCode { get; set; }
        public string InvoiceUrl { get; set; }
    }
}
