//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceRequire
    {
        public int Id { get; set; }
        public int ComId { get; set; }
        public int StatementId { get; set; }
        public string InvoiceName { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceContent { get; set; }
        public decimal InvoiceAmount { get; set; }
        public string InvoiceMemo { get; set; }
        public string InvoiceStatus { get; set; }
        public int UserId { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int MemberInvoiceId { get; set; }
        public string applicationNo { get; set; }
    }
}
