//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAddress
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public string RealName { get; set; }
        public string Address { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Street { get; set; }
        public string Mansion { get; set; }
        public string Room { get; set; }
        public string TelPhone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> IsDefault { get; set; }
        public string IdCard { get; set; }
    }
}
