//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public string LoginName { get; set; }
        public string PassWord { get; set; }
        public string RealName { get; set; }
        public string Telphone { get; set; }
        public string Mobile { get; set; }
        public int Status { get; set; }
        public Nullable<int> LoginNumber { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public double Point { get; set; }
        public int ComId { get; set; }
        public int DeptId { get; set; }
        public int IsMainContact { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Street { get; set; }
        public string Mansion { get; set; }
        public string Room { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int IsThirdLogin { get; set; }
        public string Email { get; set; }
        public int IsAdmin { get; set; }
        public string RegisterMethod { get; set; }
        public int BranchId { get; set; }
        public int ConfirmLevel { get; set; }
        public string SecrecyId { get; set; }
        public System.DateTime ExportDate { get; set; }
        public int IsOrderAuthority { get; set; }
        public int IsVisible { get; set; }
        public int IsCheckMobile { get; set; }
        public int IsCheckEmail { get; set; }
        public int GoodsVisibleLevel { get; set; }
    }
}
