//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int NewsTypeId { get; set; }
        public string NewsKeywords { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string ImageUrl { get; set; }
        public string Content { get; set; }
        public int Recommend { get; set; }
        public string Describe { get; set; }
        public int BranchId { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int IsCheck { get; set; }
    }
}
