//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int GoodsId { get; set; }
        public string Model { get; set; }
        public int Num { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal SalePrice { get; set; }
        public decimal Price { get; set; }
        public int IsGift { get; set; }
        public Nullable<decimal> InPrice { get; set; }
        public decimal TaxInPrice { get; set; }
        public Nullable<decimal> AC { get; set; }
        public decimal Point { get; set; }
        public decimal Amount { get; set; }
        public int IsLack { get; set; }
        public string PurchaseStatus { get; set; }
        public string PurchaseMemo { get; set; }
        public int PickNum { get; set; }
        public string SkuName { get; set; }
        public int OldGoodsId { get; set; }
        public int GroupParentId { get; set; }
        public int IsShow { get; set; }
        public int IsCalc { get; set; }
        public decimal TaxAC { get; set; }
    }
}
