//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatusDetail
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int Userid { get; set; }
        public string Status { get; set; }
        public int IsInner { get; set; }
        public System.DateTime OperateTime { get; set; }
        public string UserName { get; set; }
        public int StatusId { get; set; }
        public string TPIStatus { get; set; }
    }
}
