//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDelivery
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int DeliveryUserId { get; set; }
        public int DistributeUserId { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int PrintNum { get; set; }
        public string Address { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    }
}
