//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ServiceId { get; set; }
        public string ServiceStatus { get; set; }
        public Nullable<System.DateTime> ServiceFinishTime { get; set; }
        public string PurchaseStatus { get; set; }
        public Nullable<System.DateTime> PurchaseFinishTime { get; set; }
        public string StoreStatus { get; set; }
        public Nullable<System.DateTime> StoreFinishTime { get; set; }
        public int PackageNum { get; set; }
        public string FeedBackStatus { get; set; }
        public Nullable<System.DateTime> FeedBackFinishTime { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<System.DateTime> DeliveryFinishTime { get; set; }
        public string OrderMemo { get; set; }
        public Nullable<int> OrderMemoUserId { get; set; }
        public Nullable<System.DateTime> OrderMemoUpdateTime { get; set; }
    }
}
