//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderReceiveMoney
    {
        public int Id { get; set; }
        public int BranchId { get; set; }
        public int OrderStatementId { get; set; }
        public decimal ReceiveMoney { get; set; }
        public string PayStatus { get; set; }
        public int BankAccountId { get; set; }
        public string PayType { get; set; }
        public string Memo { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public decimal ChargeOff { get; set; }
    }
}
