//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int ComId { get; set; }
        public int MemberId { get; set; }
        public System.DateTime OrderTime { get; set; }
        public System.DateTime PlanDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<decimal> SumMoney { get; set; }
        public Nullable<decimal> GrossProfit { get; set; }
        public Nullable<decimal> Point { get; set; }
        public string RealName { get; set; }
        public string Mobile { get; set; }
        public string Telphone { get; set; }
        public string Email { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string DeptName { get; set; }
        public string Invoice { get; set; }
        public string Invoice_Name { get; set; }
        public string Invoice_Type { get; set; }
        public string Invoice_Content { get; set; }
        public string pay_method { get; set; }
        public string Memo { get; set; }
        public int UserId { get; set; }
        public int SaveNum { get; set; }
        public int PrintNum { get; set; }
        public System.DateTime PrintDateTime { get; set; }
        public string OrderType { get; set; }
        public string PayStatus { get; set; }
        public int IsInner { get; set; }
        public int BranchId { get; set; }
        public int RowNum { get; set; }
        public int IsCopied { get; set; }
        public int RawOrderId { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int Emergency { get; set; }
        public decimal ChargeOff { get; set; }
        public decimal PaidMoney { get; set; }
        public int TPI_OrderId { get; set; }
        public int salesId { get; set; }
        public int SecrecyId { get; set; }
        public int DeptId { get; set; }
        public int ApplyId { get; set; }
        public int IsDelete { get; set; }
        public string TPI_Name { get; set; }
        public string GUID { get; set; }
        public int IsStorage { get; set; }
        public decimal Tax { get; set; }
        public double TaxRate { get; set; }
        public decimal TaxGrossProfit { get; set; }
        public int ParentOrderId { get; set; }
        public int RelationOrderId { get; set; }
    }
}
