//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string PCode { get; set; }
        public string Name { get; set; }
        public Nullable<int> level { get; set; }
        public System.DateTime createTime { get; set; }
        public int previouslevel { get; set; }
    }
}
