//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public int Id { get; set; }
        public int PurchaseId { get; set; }
        public int GoodsId { get; set; }
        public int StoreId { get; set; }
        public string Model { get; set; }
        public decimal BillsPrice { get; set; }
        public decimal InPrice { get; set; }
        public int Num { get; set; }
        public decimal Amount { get; set; }
        public int OldStore { get; set; }
        public decimal OldAC { get; set; }
        public int OldGoodsId { get; set; }
        public int ReceivedNum { get; set; }
        public int Emergency { get; set; }
        public decimal TaxInPrice { get; set; }
    }
}
