//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTarget
    {
        public int Id { get; set; }
        public int SalesId { get; set; }
        public System.DateTime YearMonth { get; set; }
        public int Target { get; set; }
        public decimal Finish { get; set; }
        public decimal FinishRatio { get; set; }
        public decimal NewCustomer { get; set; }
        public decimal OldCustormer { get; set; }
        public decimal NewGrossProfit { get; set; }
        public decimal OldGrossProfit { get; set; }
        public decimal GrossProfit { get; set; }
        public decimal SaleCost { get; set; }
        public decimal ProfitRatio { get; set; }
        public decimal ProfitFactor { get; set; }
        public decimal Commission { get; set; }
        public int CommissionConfirm { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public decimal OverdueFactor { get; set; }
        public decimal Ammount { get; set; }
        public int AmmountConfirm { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public decimal NormalCost { get; set; }
        public decimal DLHSCost { get; set; }
    }
}
