//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_bak20171018
    {
        public int ID { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string Company { get; set; }
        public string ShortName { get; set; }
        public string Type { get; set; }
        public string Attitude { get; set; }
        public string InvoiceType { get; set; }
        public string PayType { get; set; }
        public Nullable<int> YearTarget { get; set; }
        public Nullable<decimal> MonthAmount { get; set; }
        public string LinkMan1 { get; set; }
        public string TelPhone1 { get; set; }
        public string Mobile1 { get; set; }
        public string QQ1 { get; set; }
        public string LinkMan2 { get; set; }
        public string TelPhone2 { get; set; }
        public string Mobile2 { get; set; }
        public string QQ2 { get; set; }
        public string Address { get; set; }
        public string MainBrand { get; set; }
        public string Major { get; set; }
        public int BillsDiscount { get; set; }
        public int PriceSheet { get; set; }
        public int AutoOrder { get; set; }
        public int BranchId { get; set; }
        public int IsInner { get; set; }
        public string ContractType { get; set; }
        public string IsChangRefund { get; set; }
        public string PurchasRewards { get; set; }
        public string PaymentMethod { get; set; }
        public string AccountNum { get; set; }
        public string TaxpayerIdentificationCode { get; set; }
        public string OpenBank { get; set; }
        public string FinancialLinkMan { get; set; }
        public string FinancialTelPhone { get; set; }
        public string Other { get; set; }
        public int GoodsTypeId { get; set; }
        public string PY { get; set; }
        public double TaxRate { get; set; }
    }
}
