//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users
    {
        public int Id { get; set; }
        public string LoginName { get; set; }
        public string PassWord { get; set; }
        public string Name { get; set; }
        public int BranchId { get; set; }
        public int DeptId { get; set; }
        public int IsSales { get; set; }
        public string Telphone { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<int> IsYinLi { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string IDCard { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public int IsValid { get; set; }
        public string Position { get; set; }
        public string SN1 { get; set; }
        public string SN2 { get; set; }
        public int IsAdmin { get; set; }
        public string token { get; set; }
        public System.DateTime tokenEndDate { get; set; }
    }
}
