//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPI_Project
    {
        public TPI_Project()
        {
            this.test_tpi_goods = new HashSet<test_tpi_goods>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int IsUseTypeCompare { get; set; }
        public int IsUseBrandCompare { get; set; }
        public int BranchId { get; set; }
        public string Developers { get; set; }
        public int PortNumber { get; set; }
        public string Note { get; set; }
        public int IsHaveHomeImg { get; set; }
        public int IsHaveParameter { get; set; }
        public int IsHaveDetailImg { get; set; }
        public string Url { get; set; }
        public int PushType { get; set; }
        public int IsDiscount { get; set; }
        public Nullable<int> stockType { get; set; }
    
        public virtual ICollection<test_tpi_goods> test_tpi_goods { get; set; }
    }
}
