//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPI_SupplierOrder
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public string RealName { get; set; }
        public string Address { get; set; }
        public string DetailStreet { get; set; }
        public string ZipCode { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Memo { get; set; }
        public decimal Amount { get; set; }
        public decimal ShipFree { get; set; }
        public string GoodsList { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int UsersId { get; set; }
    }
}
