//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPI_Users
    {
        public int Id { get; set; }
        public string AppKey { get; set; }
        public string AppSecret { get; set; }
        public string Sign { get; set; }
        public string InterfaceVersion { get; set; }
        public string Name { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int State { get; set; }
        public int ProjectId { get; set; }
        public string AppPassword { get; set; }
        public string ClientSecret { get; set; }
    }
}
