//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPI_Goods
    {
        public int Id { get; set; }
        public string Sku { get; set; }
        public string SkuName { get; set; }
        public Nullable<decimal> ReferencePrice { get; set; }
        public decimal AgreementPrice { get; set; }
        public int GoodsId { get; set; }
        public Nullable<int> IshaveImage { get; set; }
        public Nullable<int> IsUnitAgreement { get; set; }
        public int State { get; set; }
        public int ProjectId { get; set; }
        public int Stock { get; set; }
        public int PushState { get; set; }
        public string ResultMsg { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public int ComId { get; set; }
        public string ThirdGoodsName { get; set; }
    }
}
