//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPI_GoodsType
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category { get; set; }
        public string CategoryCode { get; set; }
        public int CategorysortId1 { get; set; }
        public int CategorysortId2 { get; set; }
        public int CategorysortId3 { get; set; }
        public string MaterialId { get; set; }
    }
}
