//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPI_HNSCGoods
    {
        public int Id { get; set; }
        public string LBBH { get; set; }
        public string LBMC { get; set; }
        public string PMBH { get; set; }
        public string PMMC { get; set; }
        public string PPBH { get; set; }
        public string PPMC { get; set; }
        public string XHBH { get; set; }
        public string XHMC { get; set; }
        public string xyghbh { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
