//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPI_Category
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category { get; set; }
        public int CategoryId { get; set; }
        public string TypeName { get; set; }
        public int TypeId { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string CategoryCode { get; set; }
        public decimal Discount { get; set; }
        public int UserId { get; set; }
        public string MaterialId { get; set; }
        public Nullable<int> hasSPU { get; set; }
    }
}
