//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPI_Refund
    {
        public int id { get; set; }
        public int projectId { get; set; }
        public System.DateTime createTime { get; set; }
        public string orderRefundId { get; set; }
        public Nullable<int> origOrderId { get; set; }
        public Nullable<int> refundOrderId { get; set; }
        public string commodityId { get; set; }
        public string skuId { get; set; }
        public Nullable<int> refundNum { get; set; }
        public Nullable<decimal> refundAmt { get; set; }
        public Nullable<System.DateTime> refundTime { get; set; }
        public string refundReason { get; set; }
        public string refundName { get; set; }
        public string refundMobile { get; set; }
        public string refundTelephone { get; set; }
        public string refundDescription { get; set; }
        public Nullable<byte> refundType { get; set; }
        public string storeId { get; set; }
        public Nullable<decimal> refundIntelAmt { get; set; }
        public Nullable<decimal> refundCouponAmt { get; set; }
        public Nullable<byte> refundResult { get; set; }
        public Nullable<System.DateTime> orderRefundTime { get; set; }
        public string orderRefundDesc { get; set; }
        public Nullable<int> orderId { get; set; }
        public string questionPic { get; set; }
        public string packageDesc { get; set; }
        public Nullable<int> TPI_AfterSaleAddressPickId { get; set; }
        public Nullable<int> TPI_AfterSaleAddressReturnId { get; set; }
        public string email { get; set; }
        public string zip { get; set; }
    }
}
