//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPI_OrderDetail
    {
        public int Id { get; set; }
        public int TPI_OrderId { get; set; }
        public int GoodsId { get; set; }
        public string SkuName { get; set; }
        public int Num { get; set; }
        public decimal AgreementPrice { get; set; }
        public decimal Price { get; set; }
        public decimal Amount { get; set; }
        public string prDetailId { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<int> InvoiceRequireId { get; set; }
        public Nullable<int> orderId { get; set; }
    }
}
