//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int Id { get; set; }
        public int OutBranchId { get; set; }
        public int InBranchId { get; set; }
        public int OutStoreId { get; set; }
        public int OutStoreUserId { get; set; }
        public int InStoreId { get; set; }
        public int InStoreUserId { get; set; }
        public string Memo { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.DateTime> OutStoreDate { get; set; }
        public Nullable<System.DateTime> InStoreDate { get; set; }
        public string Status { get; set; }
        public int IsInner { get; set; }
    }
}
