//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIPCounterDetail
    {
        public int Id { get; set; }
        public int CounterId { get; set; }
        public int GoodsId { get; set; }
        public decimal VIPPrice { get; set; }
        public string Remark { get; set; }
        public System.DateTime ExportDate { get; set; }
        public int Level { get; set; }
        public int IsSales { get; set; }
        public int IsSpecial { get; set; }
    }
}
